export const HTTP_STATUS: { [key: number]: { zh: string; en: string } } = {
    100: { en: "Continue", zh: "继续" },
    101: { en: "Switching Protocols", zh: "切换协议" },
    102: { en: "Processing", zh: "处理中" },
    103: { en: "Early Hints", zh: "早期提示" },
    200: { en: "OK", zh: "成功" },
    201: { en: "Created", zh: "已创建" },
    202: { en: "Accepted", zh: "已接受" },
    203: { en: "Non-Authoritative Information", zh: "非权威信息" },
    204: { en: "No Content", zh: "无内容" },
    205: { en: "Reset Content", zh: "重置内容" },
    206: { en: "Partial Content", zh: "部分内容" },
    207: { en: "Multi-Status", zh: "多状态" },
    208: { en: "Already Reported", zh: "已报告" },
    214: { en: "Transformation Applied", zh: "已应用转换" },
    226: { en: "IM Used", zh: "IM已使用" },
    300: { en: "Multiple Choices", zh: "多个选择" },
    301: { en: "Moved Permanently", zh: "永久移动" },
    302: { en: "Found", zh: "找到" },
    303: { en: "See Other", zh: "查看其他" },
    304: { en: "Not Modified", zh: "未修改" },
    305: { en: "Use Proxy", zh: "使用代理" },
    307: { en: "Temporary Redirect", zh: "临时重定向" },
    400: { en: "Bad Request", zh: "错误请求" },
    401: { en: "Unauthorized", zh: "未授权" },
    403: { en: "Forbidden", zh: "禁止" },
    404: { en: "Not Found", zh: "未找到" },
    405: { en: "Method Not Allowed", zh: "方法不允许" },
    406: { en: "Not Acceptable", zh: "不可接受" },
    407: { en: "Proxy Authentication Required", zh: "需要代理身份验证" },
    408: { en: "Request Timeout", zh: "请求超时" },
    409: { en: "Conflict", zh: "冲突" },
    410: { en: "Gone", zh: "已删除" },
    411: { en: "Length Required", zh: "需要内容长度" },
    412: { en: "Precondition Failed", zh: "先决条件失败" },
    413: { en: "Request Entity Too Large", zh: "请求实体过大" },
    414: { en: "Request-URI Too Long", zh: "请求URI过长" },
    415: { en: "Unsupported Media Type", zh: "不支持的媒体类型" },
    416: { en: "Requested Range Not Satisfiable", zh: "请求范围不可满足" },
    417: { en: "Expectation Failed", zh: "期望失败" },
    418: { en: "I'm a teapot", zh: "我是个泡泡茶壶" },
    420: { en: "Enhance Your Calm", zh: "冷静" },
    421: { en: "Misdirected Request", zh: "误导请求" },
    423: { en: "Locked", zh: "锁定" },
    424: { en: "Failed Dependency", zh: "依赖失败" },
    425: { en: "Too Early", zh: "太早" },
    426: { en: "Upgrade Required", zh: "需要升级" },
    428: { en: "Precondition Required", zh: "需要先决条件" },
    429: { en: "Too Many Requests", zh: "太多请求" },
    431: { en: "Request Header Fields Too Large", zh: "请求头字段太大" },
    444: { en: "No Response", zh: "无响应" },
    450: { en: "Blocked by Windows Parental Controls", zh: "被Windows家长控制阻止" },
    451: { en: "Unavailable For Legal Reasons", zh: "因法律原因不可用" },
    497: { en: "HTTP Request Sent to HTTPS Port", zh: "HTTP请求发送到HTTPS端口" },
    498: { en: "Token expired/invalid", zh: "令牌过期/无效" },
    500: { en: "Internal Server Error", zh: "内部服务器错误" },
    501: { en: "Not Implemented", zh: "未实现" },
    502: { en: "Bad Gateway", zh: "网关错误" },
    503: { en: "Service Unavailable", zh: "服务不可用" },
    504: { en: "Gateway Timeout", zh: "网关超时" },
    505: { en: "HTTP Version Not Supported", zh: "HTTP版本不支持" },
    506: { en: "Variant Also Negotiates", zh: "透明内容协商" },
    507: { en: "Insufficient Storage", zh: "存储不足" },
    508: { en: "Loop Detected", zh: "检测到循环" },
    510: { en: "Not Extended", zh: "未扩展" },
    511: { en: "Network Authentication Required", zh: "需要网络认证" },
    509: { en: "Bandwidth Limit Exceeded", zh: "超出带宽限制" },
    521: { en: "Web Server Is Down", zh: "Web服务器已关闭" },
    522: { en: "Connection Timed Out", zh: "连接超时" },
    523: { en: "Origin Is Unreachable", zh: "源不可达" },
    525: { en: "SSL Handshake Failed", zh: "SSL握手失败" },
    530: { en: "Site Frozen", zh: "站点冻结" },
    599: { en: "Network connect timeout error", zh: "网络连接超时错误" },
};
